### ISSUE TITLE
Escape symbols in query

### ISSUE THREAD

**Issue by sonicer105** [irisarco/derpibooru-tagging-helper#1]
Both `>` and `)` need to be escaped or quoted in certain situations. 

Adding the tag `>:)` causes the load related button to return a 400 error and no cors headers. The error returned is:

```JSON
{"error":"junk at end of expression: ),score.gt:50,first_seen_at.lt:2 days ago"}
```

You need to escape `>:)` as `\>:\)` or wrap it in quotations for it to work properly in the request. 

So the URL

```
https://derpibooru.org/api/v1/json/search/images?q=%28%3E%3A%29%29%2C+score.gt%3A50%2C+first_seen_at.lt%3A2+days+ago&filter_id=56027&sf=_score&per_page=50
```

should be written as

```
https://derpibooru.org/api/v1/json/search/images?q=%28%5C%3E%3A%5C%29%29%2C+score.gt%3A50%2C+first_seen_at.lt%3A2+days+ago&filter_id=56027&sf=_score&per_page=50
```

Hope this helps

**Comment by irisarco** [comment]
Hi, thanks for the bug report. It's good to know someone actually used this project :)

It should be fixed in 388a6fa3e69a7d9e74b5cca955945531807aecd6
